services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana_data:/var/lib/grafana

  loki:
    image: grafana/loki
    ports:
      - 3100:3100
    restart: unless-stopped
    volumes:
      - ./loki/local-config.yaml:/etc/loki/local-config.yaml
      - loki_data:/loki
      
  busybox:
    image: busybox
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - while true; do echo "$(date) - busybox"; sleep 1; done

volumes:
  grafana_data:
  loki_data:
